// Mentegraf — D3.js Publish Template
// Generates standalone interactive HTML with force layout

function doPublish(){
var nd=[],ed=[];
cy.nodes().forEach(function(n){var d=n.data(),p=n.position();nd.push({id:d.id,label:d.label,type:d.type,color:d.color,description:d.description||'',notes:d.notes||'',x:p.x,y:p.y})});
cy.edges().forEach(function(e){var d=e.data();ed.push({source:d.source,target:d.target,weight:d.weight||1,edgeType:d.edgeType||'',note:d.note||''})});
var cm={};categories.forEach(function(c){cm[c.id]={label:catLabel(c),color:c.color,svgPath:c.svgPath}});
var ct={};connTypes.forEach(function(c){ct[c.id]={label:connLabel(c),color:c.color||'#888',marker:c.marker||'',style:c.style||'solid'}});

var pubLang=curLang;
var pubLabels={
  search:L('search'),detail:L('nodeDetail'),connections:L('connections'),
  fit:'Fit',theme:L('themes')?L('themes').split('/')[0]:'Theme'
};
var S='<'+'/'+'script>';
var H='<!DOCTYPE html>\n<html lang="'+pubLang+'"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n'
+'<title>Mentegraf</title>\n'
+'<script src="https://d3js.org/d3.v7.min.js">'+S+'\n'
+'<style>\n'
+':root{--bg:#0f0f16;--text:#e8e5dc;--dim:#a09a88;--border:rgba(255,255,255,.08);--panel:#181820;--accent:#c5a05e;--hover:rgba(255,255,255,.12)}\n'
+'[data-theme=light]{--bg:#f5f2ec;--text:#2c2820;--dim:#7a7262;--border:rgba(0,0,0,.09);--panel:#fff;--accent:#9a7a3a;--hover:rgba(0,0,0,.08)}\n'
+'*{margin:0;padding:0;box-sizing:border-box}\n'
+'body{background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,sans-serif;overflow:hidden;height:100vh;transition:background .3s,color .3s}\n'
+'svg.graph{width:100%;height:100vh}\n'
+'.node{cursor:pointer}.node text{font-size:11px;fill:var(--text);pointer-events:none}\n'
+'.link{stroke-linecap:round}\n'
+'.edge-label{font-size:11px;fill:var(--dim);pointer-events:none;text-anchor:middle;dominant-baseline:central}\n'
+'#topbar{position:fixed;top:0;left:0;right:0;height:44px;background:var(--panel);border-bottom:1px solid var(--border);display:flex;align-items:center;padding:0 14px;gap:8px;z-index:20}\n'
+'#topbar input{padding:6px 10px;border-radius:6px;border:1px solid var(--border);background:var(--bg);color:var(--text);font-size:13px;outline:none;width:180px}\n'
+'#topbar input:focus{border-color:var(--accent);width:220px}\n'
+'#topbar input::placeholder{color:var(--dim)}\n'
+'.tbtn{padding:5px 10px;border-radius:6px;border:1px solid var(--border);background:transparent;color:var(--dim);font-size:12px;cursor:pointer;transition:all .15s;display:flex;align-items:center;gap:4px}\n'
+'.tbtn:hover{color:var(--text);background:var(--hover)}\n'
+'.tbtn.active{border-color:var(--accent);color:var(--text)}\n'
+'.tsep{width:1px;height:20px;background:var(--border)}\n'
+'.filters{display:flex;gap:4px;align-items:center;flex-wrap:nowrap;overflow-x:auto}\n'
+'.fb{padding:3px 8px;border-radius:5px;border:1px solid var(--border);background:transparent;cursor:pointer;font-size:11px;display:flex;align-items:center;gap:4px;transition:all .15s;color:var(--dim);white-space:nowrap}\n'
+'.fb:hover{border-color:var(--hover)}.fb.on{border-color:var(--accent);color:var(--text)}\n'
+'.fdot{width:7px;height:7px;border-radius:50%;flex-shrink:0}\n'
+'#detailPanel{position:fixed;top:44px;right:0;bottom:0;width:320px;background:var(--panel);border-left:1px solid var(--border);transform:translateX(100%);transition:transform .25s ease;z-index:18;display:flex;flex-direction:column;box-shadow:-4px 0 20px rgba(0,0,0,.2)}\n'
+'#detailPanel.open{transform:translateX(0)}\n'
+'.dp-head{padding:14px 16px;font-size:12px;color:var(--dim);text-transform:uppercase;letter-spacing:.06em;border-bottom:1px solid var(--border);display:flex;justify-content:space-between;align-items:center}\n'
+'.dp-head button{background:none;border:none;color:var(--dim);cursor:pointer;font-size:16px}.dp-head button:hover{color:var(--text)}\n'
+'.dp-body{flex:1;overflow-y:auto;padding:16px}\n'
+'.dp-body::-webkit-scrollbar{width:4px}.dp-body::-webkit-scrollbar-thumb{background:var(--border);border-radius:2px}\n'
+'.dp-name{font-size:18px;font-weight:500;color:var(--text);margin-bottom:4px}\n'
+'.dp-type{font-size:10px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:12px;display:inline-block;padding:2px 8px;border-radius:4px}\n'
+'.dp-desc{font-size:13px;line-height:1.6;color:var(--dim);margin-bottom:16px}\n'
+'.dp-section{font-size:10px;color:var(--dim);text-transform:uppercase;letter-spacing:.06em;margin:12px 0 8px}\n'
+'.dp-conn{padding:6px 8px;border-radius:6px;font-size:12px;cursor:pointer;display:flex;justify-content:space-between;align-items:center;margin-bottom:3px;transition:background .1s}\n'
+'.dp-conn:hover{background:var(--hover)}\n'
+'.dp-dot{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:6px}\n'
+'#zoom-controls{position:fixed;bottom:16px;right:16px;display:flex;flex-direction:column;gap:4px;z-index:15}\n'
+'#zoom-controls button{width:36px;height:36px;border-radius:8px;border:1px solid var(--border);background:var(--panel);color:var(--dim);font-size:18px;cursor:pointer;display:flex;align-items:center;justify-content:center}\n'
+'#zoom-controls button:hover{color:var(--text);border-color:var(--accent)}\n'
+'#stats{position:fixed;bottom:12px;left:14px;font-size:11px;color:var(--dim);z-index:15}\n'
+'</style></head><body>\n'
+'<div id="topbar">\n'
+'<input type="text" id="srch" placeholder="'+pubLabels.search+'" oninput="doSearch(this.value)">\n'
+'<div class="tsep"></div>\n'
+'<div class="filters" id="filters"></div>\n'
+'<div style="margin-left:auto;display:flex;gap:6px">\n'
+'<button class="tbtn" onclick="toggleTheme()">'+pubLabels.theme+'</button>\n'
+'<button class="tbtn" onclick="zoomFit()">Fit</button>\n'
+'</div>\n'
+'</div>\n'
+'<div id="detailPanel"><div class="dp-head"><span>'+pubLabels.detail+'</span><button onclick="closeDetail()">✕</button></div><div class="dp-body" id="dpBody"></div></div>\n'
+'<div id="zoom-controls"><button onclick="zoomIn()">+</button><button onclick="zoomOut()">−</button></div>\n'
+'<div id="stats"></div>\n'
+'<'+'script>\n'
+'var nodes='+JSON.stringify(nd)+';\n'
+'var links='+JSON.stringify(ed)+';\n'
+'var cats='+JSON.stringify(cm)+';\n'
+'var edgeTypes='+JSON.stringify(ct)+';\n'
+'var theme="dark",w=innerWidth,h=innerHeight;\n'
+'var activeTypes=new Set(Object.keys(cats));\n'
+'var selectedNode=null;\n'
+'\n'
+'var svg=d3.select("body").append("svg").attr("class","graph").attr("viewBox",[0,0,w,h]);\n'
+'var g=svg.append("g");\n'
+'var zoom=d3.zoom().scaleExtent([.05,8]).on("zoom",function(e){g.attr("transform",e.transform)});\n'
+'svg.call(zoom);\n'
+'\n'
+'// SVG defs for node icons\n'
+'var defs=svg.append("defs");\n'
+'Object.entries(cats).forEach(function(kv){var k=kv[0],c=kv[1];defs.append("g").attr("id","ic-"+k).append("path").attr("d",c.svgPath).attr("fill","white").attr("opacity","0.85").attr("transform","scale(0.58)");});\n'
+'\n'
+'// Build filters\n'
+'var fDiv=document.getElementById("filters");\n'
+'Object.entries(cats).forEach(function(kv){\n'
+'  var k=kv[0],c=kv[1];\n'
+'  var b=document.createElement("button");b.className="fb on";b.dataset.type=k;\n'
+'  b.innerHTML=\'<span class="fdot" style="background:\'+c.color+\'"></span>\'+c.label;\n'
+'  b.onclick=function(){if(activeTypes.has(k)){if(activeTypes.size>1){activeTypes.delete(k);b.classList.remove("on")}}else{activeTypes.add(k);b.classList.add("on")}applyFilters()};\n'
+'  fDiv.appendChild(b);\n'
+'});\n'
+'\n'
+'// Create link index for edge lookup\n'
+'var nodeMap={};nodes.forEach(function(n){nodeMap[n.id]=n});\n'
+'\n'
+'// D3 force simulation\n'
+'var simulation=d3.forceSimulation(nodes)\n'
+'  .force("link",d3.forceLink(links).id(function(d){return d.id}).distance(function(d){return 140-d.weight*8}).strength(function(d){return 0.3+d.weight*0.05}))\n'
+'  .force("charge",d3.forceManyBody().strength(-300).distanceMax(500))\n'
+'  .force("center",d3.forceCenter(w/2,h/2))\n'
+'  .force("collision",d3.forceCollide(30))\n'
+'  .force("x",d3.forceX(w/2).strength(0.03))\n'
+'  .force("y",d3.forceY(h/2).strength(0.03));\n'
+'\n'
+'// Use preset positions as initial then let force settle\n'
+'nodes.forEach(function(n){n.fx=null;n.fy=null});\n'
+'\n'
+'// Draw edges\n'
+'var link=g.append("g").selectAll("line").data(links).join("line")\n'
+'  .attr("class","link")\n'
+'  .attr("stroke",function(d){var et=edgeTypes[d.edgeType]||edgeTypes[""];return et?et.color:"rgba(255,255,255,.12)"})\n'
+'  .attr("stroke-width",function(d){return Math.max(1,d.weight*1.2)})\n'
+'  .attr("stroke-opacity",.25)\n'
+'  .attr("stroke-dasharray",function(d){var et=edgeTypes[d.edgeType];if(!et)return null;if(et.style==="dashed")return"6 4";if(et.style==="dotted")return"2 3";return null});\n'
+'\n'
+'// Edge markers (text labels on edges)\n'
+'var edgeLabel=g.append("g").selectAll("text").data(links.filter(function(d){var et=edgeTypes[d.edgeType];return et&&et.marker})).join("text")\n'
+'  .attr("class","edge-label")\n'
+'  .text(function(d){return edgeTypes[d.edgeType].marker})\n'
+'  .attr("fill",function(d){return edgeTypes[d.edgeType].color})\n'
+'  .attr("font-size",13);\n'
+'\n'
+'// Draw nodes\n'
+'var node=g.append("g").selectAll("g").data(nodes).join("g")\n'
+'  .attr("class","node")\n'
+'  .call(d3.drag().on("start",dragStart).on("drag",dragging).on("end",dragEnd));\n'
+'\n'
+'node.append("circle").attr("r",18).attr("fill",function(d){return d.color}).attr("stroke",function(d){return d.color}).attr("stroke-width",2).attr("stroke-opacity",.3);\n'
+'node.append("use").attr("href",function(d){return "#ic-"+d.type}).attr("x",-7).attr("y",-7);\n'
+'node.append("text").text(function(d){return d.label}).attr("dy",32).attr("text-anchor","middle");\n'
+'\n'
+'// Tick\n'
+'simulation.on("tick",function(){\n'
+'  link.attr("x1",function(d){return d.source.x}).attr("y1",function(d){return d.source.y}).attr("x2",function(d){return d.target.x}).attr("y2",function(d){return d.target.y});\n'
+'  edgeLabel.attr("x",function(d){return(d.source.x+d.target.x)/2}).attr("y",function(d){return(d.source.y+d.target.y)/2});\n'
+'  node.attr("transform",function(d){return "translate("+d.x+","+d.y+")"});\n'
+'});\n'
+'\n'
+'// Interactions\n'
+'node.on("mouseover",function(ev,d){\n'
+'  link.attr("stroke-opacity",function(l){return(l.source.id===d.id||l.target.id===d.id)?.7:.04});\n'
+'  node.attr("opacity",function(n){if(n.id===d.id)return 1;var cn=links.some(function(l){return(l.source.id===d.id&&l.target.id===n.id)||(l.target.id===d.id&&l.source.id===n.id)});return cn?1:.1});\n'
+'  edgeLabel.attr("opacity",function(l){return(l.source.id===d.id||l.target.id===d.id)?1:.05});\n'
+'  d3.select(this).select("circle").attr("stroke-width",3).attr("stroke-opacity",1).attr("r",22);\n'
+'}).on("mouseout",function(){\n'
+'  if(!selectedNode){link.attr("stroke-opacity",.25);node.attr("opacity",1);edgeLabel.attr("opacity",1);d3.select(this).select("circle").attr("stroke-width",2).attr("stroke-opacity",.3).attr("r",18)}\n'
+'}).on("click",function(ev,d){\n'
+'  ev.stopPropagation();\n'
+'  showDetail(d);\n'
+'});\n'
+'\n'
+'svg.on("click",function(){closeDetail()});\n'
+'\n'
+'// Detail panel\n'
+'function showDetail(d){\n'
+'  selectedNode=d;\n'
+'  var c=cats[d.type]||{label:"",color:"#666"};\n'
+'  var conns=[];\n'
+'  links.forEach(function(l){\n'
+'    if(l.source.id===d.id){conns.push({node:nodeMap[l.target.id]||l.target,weight:l.weight,edgeType:l.edgeType,note:l.note})}\n'
+'    else if(l.target.id===d.id){conns.push({node:nodeMap[l.source.id]||l.source,weight:l.weight,edgeType:l.edgeType,note:l.note})}\n'
+'  });\n'
+'  conns.sort(function(a,b){return b.weight-a.weight});\n'
+'  var html=\'<div class="dp-name">\'+d.label+\'</div>\';\n'
+'  html+=\'<div class="dp-type" style="color:\'+c.color+\';background:\'+c.color+\'22">\'+c.label+\'</div>\';\n'
+'  if(d.description)html+=\'<div class="dp-desc">\'+d.description+\'</div>\';\n'
+'  if(conns.length){\n'
+'    html+=\'<div class="dp-section">\'+conns.length+\' '+pubLabels.connections+'</div>\';\n'
+'    conns.forEach(function(cn){\n'
+'      var nc=cats[cn.node.type]||{color:"#666"};\n'
+'      var et=edgeTypes[cn.edgeType]||{};\n'
+'      var wStr="";for(var i=0;i<5;i++)wStr+=i<cn.weight?"●":"○";\n'
+'      html+=\'<div class="dp-conn" onclick="focusNode(this,\\\'\'+cn.node.id+\'\\\')"><span><span class="dp-dot" style="background:\'+nc.color+\'"></span>\'+cn.node.label+(et.marker?\' <span style="color:\'+et.color+\'">\'+et.marker+\'</span>\':"")+\'</span><span style="font-size:9px;color:var(--dim);letter-spacing:1px">\'+wStr+\'</span></div>\';\n'
+'    });\n'
+'  }\n'
+'  document.getElementById("dpBody").innerHTML=html;\n'
+'  document.getElementById("detailPanel").classList.add("open");\n'
+'  // Highlight\n'
+'  link.attr("stroke-opacity",function(l){return(l.source.id===d.id||l.target.id===d.id)?.7:.04});\n'
+'  node.attr("opacity",function(n){if(n.id===d.id)return 1;var cn=links.some(function(l){return(l.source.id===d.id&&l.target.id===n.id)||(l.target.id===d.id&&l.source.id===n.id)});return cn?1:.1});\n'
+'}\n'
+'function closeDetail(){selectedNode=null;document.getElementById("detailPanel").classList.remove("open");link.attr("stroke-opacity",.25);node.attr("opacity",1);edgeLabel.attr("opacity",1);node.selectAll("circle").attr("stroke-width",2).attr("stroke-opacity",.3).attr("r",18)}\n'
+'function focusNode(el,id){var n=nodes.find(function(x){return x.id===id});if(n){showDetail(n);var k=d3.zoomTransform(svg.node());svg.transition().duration(500).call(zoom.transform,d3.zoomIdentity.translate(w/2-n.x*k.k,h/2-n.y*k.k).scale(k.k))}}\n'
+'\n'
+'// Drag\n'
+'function dragStart(ev,d){if(!ev.active)simulation.alphaTarget(.1).restart();d.fx=d.x;d.fy=d.y}\n'
+'function dragging(ev,d){d.fx=ev.x;d.fy=ev.y}\n'
+'function dragEnd(ev,d){if(!ev.active)simulation.alphaTarget(0);d.fx=null;d.fy=null}\n'
+'\n'
+'// Filters\n'
+'function applyFilters(){\n'
+'  node.attr("display",function(d){return activeTypes.has(d.type)?null:"none"});\n'
+'  link.attr("display",function(d){var s=typeof d.source==="object"?d.source:nodeMap[d.source];var t=typeof d.target==="object"?d.target:nodeMap[d.target];return(activeTypes.has(s.type)&&activeTypes.has(t.type))?null:"none"});\n'
+'  edgeLabel.attr("display",function(d){var s=typeof d.source==="object"?d.source:nodeMap[d.source];var t=typeof d.target==="object"?d.target:nodeMap[d.target];return(activeTypes.has(s.type)&&activeTypes.has(t.type))?null:"none"});\n'
+'  updateStats();\n'
+'}\n'
+'\n'
+'// Search\n'
+'function doSearch(q){q=q.toLowerCase().trim();if(q.length<2){node.attr("opacity",1);return}node.attr("opacity",function(d){return d.label.toLowerCase().indexOf(q)>=0?1:.08})}\n'
+'\n'
+'// Zoom controls\n'
+'function zoomIn(){svg.transition().duration(300).call(zoom.scaleBy,1.4)}\n'
+'function zoomOut(){svg.transition().duration(300).call(zoom.scaleBy,0.7)}\n'
+'function zoomFit(){simulation.stop();var minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;nodes.forEach(function(n){if(n.x<minX)minX=n.x;if(n.y<minY)minY=n.y;if(n.x>maxX)maxX=n.x;if(n.y>maxY)maxY=n.y});var bw=maxX-minX||1,bh=maxY-minY||1;var s=.85*Math.min(w/bw,h/bh);svg.transition().duration(600).call(zoom.transform,d3.zoomIdentity.translate(w/2,h/2).scale(s).translate(-(minX+maxX)/2,-(minY+maxY)/2))}\n'
+'\n'
+'function toggleTheme(){theme=theme==="dark"?"light":"dark";document.documentElement.setAttribute("data-theme",theme)}\n'
+'\n'
+'function updateStats(){var vn=nodes.filter(function(n){return activeTypes.has(n.type)}).length;var ve=links.filter(function(l){var s=typeof l.source==="object"?l.source:nodeMap[l.source];var t=typeof l.target==="object"?l.target:nodeMap[l.target];return activeTypes.has(s.type)&&activeTypes.has(t.type)}).length;document.getElementById("stats").textContent=vn+" / "+ve}\n'
+'updateStats();\n'
+'\n'
+'// Let simulation settle then fit\n'
+'setTimeout(function(){zoomFit()},2500);\n'
+S+'</body></html>';

var blob=new Blob([H],{type:'text/html'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mentegraf-published.html';document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);closeExport();showMsg(L('published'))}
